## nupmy pratice set

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
import sklearn

In [4]:
print("hello world")

hello world


In [5]:
i=45

In [6]:
print(7)

7


In [7]:
i

45

In [8]:
myarr = np.array([3,6,9,7,15] , np.int64)

In [9]:
myarr

array([ 3,  6,  9,  7, 15], dtype=int64)

In [10]:
myarr[0]

3

In [11]:
myarr[4]

15

In [12]:
myarr.shape

(5,)

In [13]:
myarr.dtype

dtype('int64')

In [14]:
myarr[4]=10

In [15]:
myarr[4]

10

##Conversion from other Python structures (i.e. lists and tuples)

In [16]:
listarr=np.array([[2,4,6],[3,6,9],[4,8,12]])

In [17]:
listarr

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [18]:
listarr.dtype

dtype('int32')

In [19]:
listarr.shape

(3, 3)

In [20]:
listarr.size

9

In [21]:
np.array({34,45,67})

array({34, 67, 45}, dtype=object)

##Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [22]:
zeros = np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
rng = np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1,4,5)

In [27]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [28]:
lspace.dtype

dtype('float64')

In [29]:
emp = np.empty((4,6))

In [30]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.90100844e-307, 1.42419938e-306, 1.33511018e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [8.45606157e-307, 6.23061763e-307, 1.78019082e-306,
        6.89805151e-307, 7.56592338e-307, 6.89807188e-307],
       [1.95821303e-306, 1.42418172e-306, 1.37961641e-306,
        1.39071445e-307, 8.45610231e-307, 2.46155235e-312]])

In [31]:
emp_like = np.empty_like(lspace)

In [32]:
emp_like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [33]:
ide = np.identity(45)

In [34]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
ide.shape

(45, 45)

In [36]:
arr = np.arange(99)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr = arr.reshape(3,33)

In [39]:
arr.shape

(3, 33)

In [40]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(3, 33)

In [43]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [44]:
ar =np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.sum(axis=0)

array([12, 15, 18])

In [47]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [48]:
ar.T #transpose of matrix or array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
ar.flat

In [50]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [51]:
ar.ndim

2

In [52]:
ar.size

9

In [53]:
ar.nbytes

36

In [54]:
one = np.array([1,3,4,634,2])

In [55]:
one.argmax() # it will give the index of heigest element 

3

In [56]:
one.argmin() # it will give the index of lowest element 

0

In [57]:
one.argsort # it will give the index series for sorting 

<function ndarray.argsort>

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ar.argmin()

0

In [60]:
ar.argmax()

8

In [61]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [62]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [63]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
ar2 = np.array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [66]:
ar2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [67]:
ar + ar2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [68]:
ar*ar2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [69]:
ar/ar2

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [70]:
ar-ar2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [72]:
ar.sum()

45

In [73]:
ar.min()

1

In [74]:
ar.max()

9

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [79]:
np.count_nonzero(ar)

9

In [80]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [81]:
ar[1,2]=0

In [82]:
np.count_nonzero(ar)

8

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [84]:
import sys # checking of memoery efficency


In [85]:
ch_ar = [4,5,0,66]

In [86]:
np_ar = np.array(ch_ar)

In [87]:
sys.getsizeof(1) * len(ch_ar)

112

In [88]:
np_ar.itemsize * np_ar.size

16